services:
  xxx:
    build: .
    image: bugfishtm/xxx:latest
    restart: always
    volumes:
      - ssl:/opt/sf_ssl
      - mysql:/var/lib/mysql
      - cache:/var/www/html/_cache
      - data:/var/www/html/_data
      - image:/var/www/html/_image
      - template:/var/www/html/_template
      - store:/var/www/html/_store
    ports:
      - 80:80
      - 443:443
    environment:
      sf_db_pass:       "${sf_db_pass}"
      sf_url:           "${sf_url}"
      sf_timezone:      "${sf_timezone}"
volumes:
  mysql:
  ssl:
  data:
  cache:
  image:
  template:
  store: